import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Onboarding: one row per user
  users: defineTable({
    name: v.string(),
    email: v.string(),
    sports: v.array(v.string()), // e.g. ["tennis"]
    createdAt: v.number(),
  }).index("by_email", ["email"]),

  // A session represents one user-uploaded video coaching session
  sessions: defineTable({
    userId: v.id("users"),
    sport: v.string(),
    videoStorageId: v.id("_storage"),
    requestedSections: v.array(v.string()),
    status: v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("complete"),
      v.literal("error")
    ),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  // Analysis produced by TwelveLabs video intelligence and MediaPipe CV scoring
  analyses: defineTable({
    sessionId: v.id("sessions"),
    twelveLabsIndexId: v.optional(v.string()),
    twelveLabsVideoId: v.optional(v.string()),
    twelveLabsResult: v.optional(v.string()),
    // Serialized AnalysisResult JSON from the frontend scoring pipeline
    poseAnalysis: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_session", ["sessionId"]),

  // Chat messages for the "Ask Your Coach" conversation
  messages: defineTable({
    sessionId: v.id("sessions"),
    role: v.union(v.literal("user"), v.literal("model")),
    content: v.string(),
    createdAt: v.number(),
  }).index("by_session", ["sessionId"]),

  // Coaching feedback generated by Gemini
  feedback: defineTable({
    sessionId: v.id("sessions"),
    analysisId: v.id("analyses"),
    summary: v.string(),
    strengths: v.array(v.string()),
    improvements: v.array(v.string()),
    drills: v.array(v.string()),
    createdAt: v.number(),
  })
    .index("by_session", ["sessionId"])
    .index("by_analysis", ["analysisId"]),
});
