import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Onboarding: one row per user
  users: defineTable({
    name: v.string(),
    email: v.string(),
    sports: v.array(v.string()), // e.g. ["tennis"]
    createdAt: v.number(),
  }).index("by_email", ["email"]),

  // Sport-specific prompt templates, one row per section
  prompts: defineTable({
    sport: v.string(),
    section: v.string(), // "forehand" | "backhand" | "serve" | "volley" | "footwork"
    name: v.string(),
    content: v.string(),
    createdAt: v.number(),
  }).index("by_sport_section", ["sport", "section"]),

  // A session represents one user-uploaded video coaching session
  sessions: defineTable({
    userId: v.id("users"),
    sport: v.string(),
    videoStorageId: v.id("_storage"),
    // Sections the user asked to analyze, parsed from their prompt
    requestedSections: v.array(v.string()),
    status: v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("complete"),
      v.literal("error")
    ),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  // Analysis produced by TwelveLabs video intelligence and/or MediaPipe CV
  analyses: defineTable({
    sessionId: v.id("sessions"),
    promptId: v.optional(v.id("prompts")),
    twelveLabsIndexId: v.optional(v.string()),
    twelveLabsVideoId: v.optional(v.string()),
    poseLandmarks: v.optional(
      v.array(
        v.array(
          v.object({
            x: v.number(),
            y: v.number(),
            z: v.number(),
            visibility: v.number(),
          })
        )
      )
    ),
    twelveLabsResult: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_session", ["sessionId"]),

  // Coaching feedback generated by Gemini
  feedback: defineTable({
    sessionId: v.id("sessions"),
    analysisId: v.id("analyses"),
    summary: v.string(),
    strengths: v.array(v.string()),
    improvements: v.array(v.string()),
    drills: v.array(v.string()),
    rawResponse: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_session", ["sessionId"])
    .index("by_analysis", ["analysisId"]),
});
