import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Sport-specific prompt templates sent to TwelveLabs for video analysis
  prompts: defineTable({
    sport: v.string(),
    name: v.string(),
    // The full prompt text sent to TwelveLabs (e.g. the tennis forehand/backhand/serve/etc. template)
    content: v.string(),
    // Ordered list of stroke/category sections covered (e.g. ["forehand", "backhand", "serve"])
    sections: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_sport", ["sport"]),

  // A session represents one user-uploaded video coaching session
  sessions: defineTable({
    sport: v.string(),
    videoStorageId: v.id("_storage"),
    status: v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("complete"),
      v.literal("error")
    ),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
  }),

  // Analysis produced by TwelveLabs video intelligence and/or MediaPipe CV
  analyses: defineTable({
    sessionId: v.id("sessions"),
    // Which prompt template was used for this analysis
    promptId: v.optional(v.id("prompts")),
    // TwelveLabs index/video IDs for retrieval
    twelveLabsIndexId: v.optional(v.string()),
    twelveLabsVideoId: v.optional(v.string()),
    // MediaPipe pose landmarks: array of frames, each frame is array of {x, y, z, visibility}
    poseLandmarks: v.optional(
      v.array(
        v.array(
          v.object({
            x: v.number(),
            y: v.number(),
            z: v.number(),
            visibility: v.number(),
          })
        )
      )
    ),
    // Raw TwelveLabs analysis results
    twelveLabsResult: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_session", ["sessionId"]),

  // Coaching feedback generated by Gemini
  feedback: defineTable({
    sessionId: v.id("sessions"),
    analysisId: v.id("analyses"),
    // Structured feedback sections
    summary: v.string(),
    strengths: v.array(v.string()),
    improvements: v.array(v.string()),
    drills: v.array(v.string()),
    // Raw Gemini response for debugging
    rawResponse: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_session", ["sessionId"])
    .index("by_analysis", ["analysisId"]),
});
